name: Prediction

on:
  push:
    branches:
      - docker_ci 

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies and train model
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python train.py

      - name: Build Docker Image
        run: docker build -t mlops-pipeline .

      - name: Run container and verify
        run: docker run mlops-pipeline python predict.py

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag mlops-pipeline ${{ secrets.DOCKER_USERNAME }}/mlops-pipeline:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mlops-pipeline:latest